### ISSUE TITLE
Additional Option for Radiative Calculation

### ISSUE THREAD

**Issue by manjay1121** [robashaw/knapsack#1]
I think it would be worth allowing for an additional input within the <radiative> portion of the program to allow the user to input the units of energy the data file of their spectra is in. 
ie. one spectra is has energy is units of eV, while another has units of nm. It would be nice if the program, via an input, could recognise this. and alter the conversion factor used to output the appropriate rate of fluorescence. 
Let me know what you think
Manjay

**Comment by robashaw** [comment]
This will be easy to do - but it doesn’t make sense to do before we know the correct factor to account for one set of units. As soon as we work that out, it’ll take less than 5 mins to add the option.

Robert
